Armado de dataframes para consultas:

In [1]:
# Importar librer√≠as
import csv
import pandas as pd
import json
import numpy as np
import ast

In [2]:
#Abrir archivo .csv a dataframe
df_1 = pd.read_csv('First_Game_genres.csv', encoding = "latin-1")

In [3]:
# Nombres de columnas
df_1.columns

Index(['genres', 'release_year', 'id', 'app_name'], dtype='object')

In [4]:
#Abrir archivo .csv a dataframe
df_2 = pd.read_csv('Third_Users.csv', encoding = "latin-1")

In [5]:
# Nombres de columnas
df_2.columns

Index(['user_id', 'items_count', 'steam_id', 'item_id', 'item_name',
       'playtime_forever'],
      dtype='object')

In [6]:
#Abrir archivo .csv a dataframe
df_3 = pd.read_csv('First_Game_tags.csv', encoding = "latin-1")

In [7]:
# Nombres de columnas
df_3.columns

Index(['title', 'tags', 'developer', 'id'], dtype='object')

In [8]:
#Abrir archivo .csv a dataframe
df_4 = pd.read_csv('First_Game_desanidadoTag.csv', encoding = "latin-1")

In [9]:
# Nombres de columnas
df_4.columns

Index(['tags', 'id'], dtype='object')

In [10]:
#Abrir archivo .csv a dataframe
df_5 = pd.read_csv('Second_Reviews.csv', encoding = "latin-1")

In [11]:
# Nombres de columnas
df_5.columns

Index(['user_id', 'item_id', 'recommend', 'sentiment_analysis', 'year'], dtype='object')

In [12]:
# Unir dataframes, uno general de df_1 y df_2
genres_final = pd.concat([df_1, df_2], axis=1)

In [13]:
# Ver nombres de columnas
genres_final.columns

Index(['genres', 'release_year', 'id', 'app_name', 'user_id', 'items_count',
       'steam_id', 'item_id', 'item_name', 'playtime_forever'],
      dtype='object')

In [14]:
# Agregarle developer
data_final = genres_final.merge(df_3[["developer"]], left_index=True, right_index=True)

In [15]:
# Dataframe con recommend y sentiment
data_sentiment = genres_final.merge(df_5[["recommend", "sentiment_analysis"]], left_index=True, right_index=True)

In [16]:
#Ver dataframe de sentiment
data_sentiment

,genres,release_year,id,app_name,user_id,items_count,steam_id,item_id,item_name,playtime_forever,recommend,sentiment_analysis
0,Action,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,10,Counter-Strike,6,True,2.0
1,Casual,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,20,Team Fortress Classic,0,True,2.0
2,Indie,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,30,Day of Defeat,7,True,2.0
3,Simulation,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,40,Deathmatch Classic,0,True,2.0
4,Strategy,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,50,Half-Life: Opposing Force,0,True,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...
30473,Action,2017.0,715740.0,"Trouble Witches Origin,additional character : ...",76561198051017916,763,76561198051017916,365050,Escape,0,True,1.0
30474,Indie,2017.0,715740.0,"Trouble Witches Origin,additional character : ...",76561198051017916,763,76561198051017916,365070,One Manga Day,0,True,1.0
30475,Action,2017.0,716081.0,"Trouble Witches Origin,additional character : ...",76561198051017916,763,76561198051017916,365270,Shadow Hunter,0,False,1.0
30476,Indie,2017.0,716081.0,"Trouble Witches Origin,additional character : ...",76561198051017916,763,76561198051017916,365300,Transmissions: Element 120,0,True,2.0
30477,Casual,NaN,548280.0,NeonBall,76561198051017916,763,76561198051017916,364690,SUPER DISTRO,0,True,2.0

In [17]:
# Visualizar dataframe con developer
data_final

,genres,release_year,id,app_name,user_id,items_count,steam_id,item_id,item_name,playtime_forever,developer
0,Action,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,10,Counter-Strike,6,Kotoshiro
1,Casual,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,20,Team Fortress Classic,0,Kotoshiro
2,Indie,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,30,Day of Defeat,7,Kotoshiro
3,Simulation,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,40,Deathmatch Classic,0,Kotoshiro
4,Strategy,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,50,Half-Life: Opposing Force,0,Kotoshiro
...,...,...,...,...,...,...,...,...,...,...,...
74832,Racing,2018.0,610660.0,Russian Roads,13lazer,398,76561197982825956,252490,Rust,2630,Laush Dmitriy Sergeevich
74833,Simulation,2018.0,610660.0,Russian Roads,13lazer,398,76561197982825956,255370,KickBeat Steam Edition,0,Laush Dmitriy Sergeevich
74834,Casual,2017.0,658870.0,EXIT 2 - Directions,13lazer,398,76561197982825956,241540,State of Decay,1249,"xropi,stev3ns"
74835,Indie,2017.0,658870.0,EXIT 2 - Directions,13lazer,398,76561197982825956,209160,Call of Duty: Ghosts,38,"xropi,stev3ns"
74836,NaN,NaN,681550.0,Maze Run VR,13lazer,398,76561197982825956,209170,Call of Duty: Ghosts - Multiplayer,249,NaN

In [18]:
# Agregar al dataframe de sentiment, developer
data_final_sentiment = data_sentiment.merge(df_3[["developer"]], left_index=True, right_index=True)

In [19]:
# Ver dataframe de sentiment
data_final_sentiment

,genres,release_year,id,app_name,user_id,items_count,steam_id,item_id,item_name,playtime_forever,recommend,sentiment_analysis,developer
0,Action,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,10,Counter-Strike,6,True,2.0,Kotoshiro
1,Casual,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,20,Team Fortress Classic,0,True,2.0,Kotoshiro
2,Indie,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,30,Day of Defeat,7,True,2.0,Kotoshiro
3,Simulation,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,40,Deathmatch Classic,0,True,2.0,Kotoshiro
4,Strategy,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,50,Half-Life: Opposing Force,0,True,2.0,Kotoshiro
...,...,...,...,...,...,...,...,...,...,...,...,...,...
30473,Action,2017.0,715740.0,"Trouble Witches Origin,additional character : ...",76561198051017916,763,76561198051017916,365050,Escape,0,True,1.0,Studio SiestA
30474,Indie,2017.0,715740.0,"Trouble Witches Origin,additional character : ...",76561198051017916,763,76561198051017916,365070,One Manga Day,0,True,1.0,Studio SiestA
30475,Action,2017.0,716081.0,"Trouble Witches Origin,additional character : ...",76561198051017916,763,76561198051017916,365270,Shadow Hunter,0,False,1.0,Studio SiestA
30476,Indie,2017.0,716081.0,"Trouble Witches Origin,additional character : ...",76561198051017916,763,76561198051017916,365300,Transmissions: Element 120,0,True,2.0,Studio SiestA
30477,Casual,NaN,548280.0,NeonBall,76561198051017916,763,76561198051017916,364690,SUPER DISTRO,0,True,2.0,Nelium Games

In [20]:
# En minutos, pasarlo a horas
data_final["playtime_forever"].unique()

array([    6,     0,     7, ...,  6444, 12595, 13130], dtype=int64)

In [21]:
# Dividir la columna playtime_forever por 60 para convertir minutos a horas
data_final["playtime_forever"] = data_final["playtime_forever"] / 60

In [22]:
# Redondear la columna playtime_forever a un solo decimal
data_final["playtime_forever"] = data_final["playtime_forever"].round(1)

In [23]:
# Dataframe con developer
data_final

,genres,release_year,id,app_name,user_id,items_count,steam_id,item_id,item_name,playtime_forever,developer
0,Action,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,10,Counter-Strike,0.1,Kotoshiro
1,Casual,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,20,Team Fortress Classic,0.0,Kotoshiro
2,Indie,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,30,Day of Defeat,0.1,Kotoshiro
3,Simulation,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,40,Deathmatch Classic,0.0,Kotoshiro
4,Strategy,2018.0,761140.0,Lost Summoner Kitty,76561197970982479,277,76561197970982479,50,Half-Life: Opposing Force,0.0,Kotoshiro
...,...,...,...,...,...,...,...,...,...,...,...
74832,Racing,2018.0,610660.0,Russian Roads,13lazer,398,76561197982825956,252490,Rust,43.8,Laush Dmitriy Sergeevich
74833,Simulation,2018.0,610660.0,Russian Roads,13lazer,398,76561197982825956,255370,KickBeat Steam Edition,0.0,Laush Dmitriy Sergeevich
74834,Casual,2017.0,658870.0,EXIT 2 - Directions,13lazer,398,76561197982825956,241540,State of Decay,20.8,"xropi,stev3ns"
74835,Indie,2017.0,658870.0,EXIT 2 - Directions,13lazer,398,76561197982825956,209160,Call of Duty: Ghosts,0.6,"xropi,stev3ns"
74836,NaN,NaN,681550.0,Maze Run VR,13lazer,398,76561197982825956,209170,Call of Duty: Ghosts - Multiplayer,4.2,NaN

In [24]:
# Ver info data
data_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 74837 entries, 0 to 74836
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   genres            71554 non-null  object
 1   release_year      72450 non-null  float64
 2   id                74834 non-null  float64
 3   app_name          74834 non-null  object
 4   user_id           74837 non-null  object
 5   items_count       74837 non-null  int64
 6   steam_id          74837 non-null  int64
 7   item_id           74837 non-null  int64
 8   item_name         74837 non-null  object
 9   playtime_forever  74837 non-null  float64
 10  developer         71358 non-null  object
dtypes: float64(3), int64(3), object(5)
memory usage: 6.9+ MB

In [25]:
#Revisar NaNs
data_final.isna().sum()

genres              3283
release_year        2387
id                     3
app_name               3
user_id                0
items_count            0
steam_id               0
item_id                0
item_name              0
playtime_forever       0
developer           3479
dtype: int64

In [26]:
# Unir columnas necesarias
genres_final_ = data_final[["genres", "release_year", "user_id", "item_name", "playtime_forever", "developer"]]

In [27]:
# Ver info
genres_final_.info()

<class 'pandas.core.frame.DataFrame'>
Index: 74837 entries, 0 to 74836
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   genres            71554 non-null  object
 1   release_year      72450 non-null  float64
 2   user_id           74837 non-null  object
 3   item_name         74837 non-null  object
 4   playtime_forever  74837 non-null  float64
 5   developer         71358 non-null  object
dtypes: float64(2), object(4)
memory usage: 4.0+ MB

In [28]:
# Cambiar tipo de dato y rellenar con 0
genres_final_["release_year"] = genres_final_["release_year"].fillna(0).astype("int32")
genres_final_["user_id"] = genres_final_["user_id"].fillna(0).astype("str")
genres_final_["playtime_forever"] = genres_final_["playtime_forever"].fillna(0).astype("float32")
genres_final_["genres"] = genres_final_["genres"].fillna(0).astype("str")
genres_final_["developer"] = genres_final_["developer"].fillna(0).astype("str")

C:\Users\56988\AppData\Local\Temp\ipykernel_15328\853942638.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genres_final_["release_year"] = genres_final_["release_year"].fillna(0).astype("int32")
C:\Users\56988\AppData\Local\Temp\ipykernel_15328\853942638.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genres_final_["user_id"] = genres_final_["user_id"].fillna(0).astype("str")
C:\Users\56988\AppData\Local\Temp\ipykernel_15328\853942638.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genres_final_["playtime_forever"] = genres_final_["playtime_forever"].fillna(0).astype("float32")
C:\Users\56988\AppData\Local\Temp\ipykernel_15328\853942638.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genres_final_["genres"] = genres_final_["genres"].fillna(0).astype("str")
C:\Users\56988\AppData\Local\Temp\ipykernel_15328\853942638.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genres_final_["developer"] = genres_final_["developer"].fillna(0).astype("str")

In [29]:
# Eliminar filas con valores NaN en 'release_year' y reindexar el DataFrame
data_final.dropna(subset=["release_year"], inplace=True)
data_final.reset_index(drop=True, inplace=True)

In [30]:
# Eliminar filas con valores NaN en 'release_year' y reindexar el DataFrame
# Supongamos que el dataframe se llama data_final
data_final = data_final[data_final["release_year"] != 0]
data_final = data_final[data_final["release_year"] != 5275]

In [31]:
# Ver valores √∫nicos
data_final["release_year"].unique()

array([2018., 2017., 1997., 1998., 2016., 2006., 2005., 2003., 2007.,
       2002., 2000., 1995., 1996., 1994., 2001., 1993., 2004., 1999.,
       2008., 2009., 1992., 1989., 2010., 2011., 2013., 2012., 2014.,
       1983., 1984., 2015., 1990., 1988., 1991., 1985., 1982., 1987.,
       1981., 1986., 2021., 2019., 1975., 1970., 1980.])

In [32]:
# Borrar de genres los nulos
data_final = data_final.dropna(subset=["genres"])

In [33]:
# Ver los valores √∫nicos de genres
data_final["genres"].unique()

array(['Action', 'Casual', 'Indie', 'Simulation', 'Strategy',
       'Free to Play', 'RPG', 'Sports', 'Adventure', 'Racing',
       'Massively Multiplayer', 'Early Access',
       'Animation &amp; Modeling', 'Video Production', 'Web Publishing',
       'Education', 'Software Training', 'Utilities',
       'Design &amp; Illustration', 'Audio Production', 'Photo Editing',
       'Accounting'], dtype=object)

In [34]:
# Verificar datos
genres_final_.info()

<class 'pandas.core.frame.DataFrame'>
Index: 74837 entries, 0 to 74836
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   genres            74837 non-null  object
 1   release_year      74837 non-null  int32
 2   user_id           74837 non-null  object
 3   item_name         74837 non-null  object
 4   playtime_forever  74837 non-null  float32
 5   developer         74837 non-null  object
dtypes: float32(1), int32(1), object(4)
memory usage: 3.4+ MB

Consultas:

Consulta n√∫mero 1:

In [35]:
# Unir columnas necesarias genres-a√±o-horas_jugadas
genres_year_playtime = data_final[["genres", "release_year", "playtime_forever"]]

In [36]:
# Revisar dataframe
genres_year_playtime

           genres  release_year  playtime_forever
0          Action        2018.0               0.1
1          Casual        2018.0               0.0
2           Indie        2018.0               0.1
3      Simulation        2018.0               0.0
4        Strategy        2018.0               0.0
...           ...           ...               ...
72445       Indie        2018.0               2.4
72446      Racing        2018.0              43.8
72447  Simulation        2018.0               0.0
72448      Casual        2017.0              20.8
72449       Indie        2017.0               0.6

[71213 rows x 3 columns]

In [37]:
# Cambiar tipo de dato
genres_year_playtime["release_year"] = genres_year_playtime["release_year"].fillna(0).astype("int32")
genres_year_playtime["playtime_forever"] = genres_year_playtime["playtime_forever"].fillna(0).astype("float32")

C:\Users\56988\AppData\Local\Temp\ipykernel_15328\23275085.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genres_year_playtime["release_year"] = genres_year_playtime["release_year"].fillna(0).astype("int32")
C:\Users\56988\AppData\Local\Temp\ipykernel_15328\23275085.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genres_year_playtime["playtime_forever"] = genres_year_playtime["playtime_forever"].fillna(0).astype("float32")

In [38]:
# Agrupar por g√©nero, a√±o y sumar las horas jugadas
grouped = genres_year_playtime.groupby(["genres", "release_year"])["playtime_forever"].sum().reset_index()

# Encontrar el a√±o con m√°s horas jugadas por g√©nero
max_playtime_by_genre_year = grouped.loc[grouped.groupby("genres")["playtime_forever"].idxmax()]

# Convertir la columna 'release_year' de flotante a entero
max_playtime_by_genre_year["release_year"] = max_playtime_by_genre_year["release_year"].astype(int)

# Mostrar el resultado
max_playtime_by_genre_year

                        genres  release_year  playtime_forever
2                   Accounting          2017         30.600000
34                      Action          2017      76282.898438
70                   Adventure          2017      64135.800781
77    Animation &amp; Modeling          2014        991.500000
81            Audio Production          2007       3319.500000
116                     Casual          2017      72348.296875
124  Design &amp; Illustration          2016       5406.200195
133               Early Access          2017      28180.699219
136                  Education          2008        518.200012
161               Free to Play          2017      16688.500000
191                      Indie          2017     119911.500000
209      Massively Multiplayer          2016       8192.700195
216              Photo Editing          2015       1135.300049
249                        RPG          2017      42725.898438
274                     Racing          2017       7388.700195
308                 Simulation          2017      49059.300781
314          Software Training          2015        619.599976
334                     Sports          2017      11193.500000
363                   Strategy          2016      43945.601562
376                  Utilities          2017       3152.399902
385           Video Production          2017       1365.099976
391             Web Publishing          2014       2465.399902

In [39]:
# Primera consulta:
def PlayTimeGenre(genero: str):
    '''Se ingresa el G√©nero y la funci√≥n retorna el A√±o con m√°s horas jugadas'''

    # Convertir el g√©nero a min√∫sculas para hacer la comparaci√≥n sin ser sensible a may√∫sculas
    genero = genero.lower()

    # Verificar si el g√©nero est√° presente en el DataFrame
    if genero not in max_playtime_by_genre_year["genres"].str.lower().unique():
        return {"Error": f"El g√©nero '{genero}' no se encuentra en el conjunto de datos."}

    # Filtrar el DataFrame por el g√©nero proporcionado
    genre_data = max_playtime_by_genre_year[max_playtime_by_genre_year["genres"].str.lower() == genero]

    # Obtener el a√±o con m√°s horas jugadas para el g√©nero dado
    max_playtime_year = genre_data["release_year"].values[0] if not genre_data.empty else None


    # Crear el diccionario para el formato JSON
    result = {f"A√±o de lanzamiento con m√°s horas jugadas para {genero.capitalize()}": str(max_playtime_year)}

    return result

In [40]:
# Ejemplo con Action
PlayTimeGenre("Massively Multiplayer")

{'A√±o de lanzamiento con m√°s horas jugadas para Massively multiplayer': '2016'}

Consulta n√∫mero 2:

In [41]:
# Unir columnas necesarias user-genres-a√±o-horas_jugadas
user_year_playtime = data_final[["user_id", "genres", "release_year", "playtime_forever"]]

In [42]:
user_year_playtime[["release_year"]] = user_year_playtime[["release_year"]].astype(int)

C:\Users\56988\AppData\Local\Temp\ipykernel_15328\4146734101.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  user_year_playtime[["release_year"]] = user_year_playtime[["release_year"]].astype(int)

In [43]:
# Ver dataframe
user_year_playtime

                 user_id      genres  release_year  playtime_forever
0      76561197970982479      Action          2018               0.1
1      76561197970982479      Casual          2018               0.0
2      76561197970982479       Indie          2018               0.1
3      76561197970982479  Simulation          2018               0.0
4      76561197970982479    Strategy          2018               0.0
...                  ...         ...           ...               ...
72445            13lazer       Indie          2018               2.4
72446            13lazer      Racing          2018              43.8
72447            13lazer  Simulation          2018               0.0
72448            13lazer      Casual          2017              20.8
72449            13lazer       Indie          2017               0.6

[71213 rows x 4 columns]

In [44]:
# Calcular la suma total de horas jugadas por usuario y g√©nero
user_genre_playtime = user_year_playtime.groupby(["user_id", "genres"])["playtime_forever"].sum().reset_index()

# Encontrar el usuario que acumula m√°s horas jugadas por g√©nero
max_playtime_per_genre = user_genre_playtime.loc[user_genre_playtime.groupby("genres")["playtime_forever"].idxmax()]

# Imprimir o trabajar con los resultados
max_playtime_per_genre

,user_id,genres,playtime_forever
4976,EndAtHallow,Accounting,30.1
5021,Forty-Nine,Action,6924.9
1323,76561198044169764,Adventure,4846.0
1354,76561198045071942,Animation &amp; Modeling,502.2
4369,Ahahahahahahahahahahahahahahaha,Audio Production,3319.5
1059,76561198035548591,Casual,4416.5
3932,76561198126640317,Design &amp; Illustration,1520.2
708,76561198016685643,Early Access,3801.3
6096,ZUERA12,Education,518.2
881,76561198028895010,Free to Play,2500.8
6705,death-hunter,Indie,4435.2
1169,76561198039778856,Massively Multiplayer,1265.1
5328,Life-Of-Blu,Photo Editing,845.2
562,76561198003688205,RPG,3421.6
1470,76561198047304525,Racing,1077.4
5162,Hummingsenpai,Simulation,3188.8
3890,76561198110293299,Software Training,353.7
7962,thequeenpanda,Sports,4283.1
2997,76561198078738103,Strategy,5067.8
240,66666669999999,Utilities,1025.9
4953,DoaFapbeforeaNap,Video Production,992.1
3376,76561198087471896,Web Publishing,1192.6

In [45]:
# Obtener los usuarios contenidos en el dataframe 'max_playtime_per_genre'
users_of_interest = max_playtime_per_genre["user_id"].unique()

# Calcular la suma total de horas jugadas por a√±o
playtime_per_year = user_year_playtime.groupby(["user_id", "release_year"])["playtime_forever"].sum().reset_index()
playtime_per_year.rename(columns={"playtime_forever": "playtime_total_minutes"}, inplace=True)

# Convertir las horas jugadas a horas en lugar de minutos
playtime_per_year["playtime_total_hours"] = playtime_per_year["playtime_total_minutes"] / 60

# Resumen de horas jugadas por a√±o de los usuarios seleccionados por g√©nero
summary_playtime_per_year = playtime_per_year.groupby(["user_id", "release_year"])["playtime_total_hours"].sum().reset_index()

summary_playtime_per_year

               user_id  release_year  playtime_total_hours
0     -AnimeIsMyThing-          2012              0.148333
1     -AnimeIsMyThing-          2013              3.230000
2     -AnimeIsMyThing-          2016             67.081667
3             -Azsael-          2011              1.861667
4             -Azsael-          2012              1.565000
...                ...           ...                   ...
2035           yookobz          2010              0.061667
2036           yookobz          2012              0.000000
2037           yookobz          2015              0.000000
2038           yookobz          2016             29.530000
2039         zomboy151          2017             28.001667

[2040 rows x 3 columns]

In [46]:
def UserForGenre(genero: str): # Este funciona con GENRE, NO CON USER!!!
    # Agrupar por usuario y a√±o, sumar las horas jugadas y encontrar el usuario con m√°s horas jugadas
    result_df = user_year_playtime.groupby(["user_id", "release_year"])["playtime_forever"].sum().reset_index()
    max_user = result_df.loc[result_df["playtime_forever"].idxmax()]

    # Convertir las horas jugadas de minutos a horas en el DataFrame resultante
    result_df["playtime_forever"] = result_df["playtime_forever"] / 60
    result_df["playtime_forever"] = result_df["playtime_forever"].round(0)

    # Crear una lista de acumulaci√≥n de horas jugadas por a√±o
    accumulation = result_df.groupby("release_year")["playtime_forever"].sum().reset_index()
    accumulation = accumulation.rename(columns={"release_year": "A√±o", "playtime_forever": "Horas"})
    accumulation_list = accumulation.to_dict(orient="records")

    return {"Usuario con m√°s horas jugadas para el g√©nero " + genero: max_user["user_id"], "Horas jugadas": accumulation_list}

In [47]:
genero = "Action"
usuario_por_genero = UserForGenre(genero)
usuario_por_genero

{'Usuario con m√°s horas jugadas para el g√©nero Action': '76561198016685643',
 'Horas jugadas': [{'A√±o': 1983, 'Horas': 1.0},
  {'A√±o': 1984, 'Horas': 0.0},
  {'A√±o': 1985, 'Horas': 0.0},
  {'A√±o': 1986, 'Horas': 0.0},
  {'A√±o': 1987, 'Horas': 0.0},
  {'A√±o': 1988, 'Horas': 0.0},
  {'A√±o': 1989, 'Horas': 1.0},
  {'A√±o': 1990, 'Horas': 2.0},
  {'A√±o': 1991, 'Horas': 0.0},
  {'A√±o': 1992, 'Horas': 8.0},
  {'A√±o': 1993, 'Horas': 3.0},
  {'A√±o': 1994, 'Horas': 12.0},
  {'A√±o': 1995, 'Horas': 14.0},
  {'A√±o': 1996, 'Horas': 18.0},
  {'A√±o': 1997, 'Horas': 23.0},
  {'A√±o': 1998, 'Horas': 34.0},
  {'A√±o': 1999, 'Horas': 6.0},
  {'A√±o': 2000, 'Horas': 24.0},
  {'A√±o': 2001, 'Horas': 66.0},
  {'A√±o': 2002, 'Horas': 32.0},
  {'A√±o': 2003, 'Horas': 14.0},
  {'A√±o': 2004, 'Horas': 21.0},
  {'A√±o': 2005, 'Horas': 58.0},
  {'A√±o': 2006, 'Horas': 55.0},
  {'A√±o': 2007, 'Horas': 122.0},
  {'A√±o': 2008, 'Horas': 82.0},
  {'A√±o': 2009, 'Horas': 68.0},
  {'A√±o': 2010, 'Horas': 83.0},
  {'A√±o': 2011, 'Horas': 192.0},
  {'A√±o': 2012, 'Horas': 598.0},
  {'A√±o': 2013, 'Horas': 843.0},
  {'A√±o': 2014, 'Horas': 2397.0},
  {'A√±o': 2015, 'Horas': 5909.0},
  {'A√±o': 2016, 'Horas': 7068.0},
  {'A√±o': 2017, 'Horas': 9108.0},
  {'A√±o': 2018, 'Horas': 165.0},
  {'A√±o': 2019, 'Horas': 2.0},
  {'A√±o': 2021, 'Horas': 0.0}]}

In [48]:
# Segunda consulta:  NO ME SALE!!!!
def UserForGenre(user: str):
    '''Se ingresa el Usuario y la funci√≥n retorna la cantidad de Horas jugadas para dicho g√©nero seg√∫n el A√±o en que ha jugado'''
    
    # Convertir el g√©nero a min√∫sculas para ser insensible a may√∫sculas/min√∫sculas
    user = user.lower()

    # Filtrar por el usuario
    user_data = max_playtime_per_genre[max_playtime_per_genre["user_id"].str.lower() == user]

    if len(user_data) == 0:
        return "Usuario no encontrado"

    # Obtener el usuario con m√°s horas jugadas para el g√©nero dado
    max_playtime_user = user_data.loc[user_data["playtime_forever"].idxmax()]["user_id"]

    # Filtrar por el g√©nero deseado en el dataframe asociado a user
    genre_year_data = user_genre_playtime[user_genre_playtime["genres"].isin(user_data["user_id"])]

    # Agrupar y sumar las horas jugadas por a√±o, excluyendo los a√±os con 0 horas jugadas
    yearly_hours = genre_year_data.groupby("release_year")["playtime_forever"].sum().reset_index()
    yearly_hours = yearly_hours[yearly_hours["playtime_forever"] > 1]
    # Crear un diccionario con el formato solicitado
    hours_by_year = [
        {"A√±o": int(year), "Horas": int(hours)}
        for year, hours in zip(yearly_hours["release_year"])
    ]

    # Formato de salida en JSON
    output = {
        f"Usuario {user.capitalize()} con m√°s horas jugadas para {genre_year_data.capitalize()}": max_playtime_user,
    "Horas jugadas": hours_by_year
    }
    return output

In [49]:
# Ejemplo de uso de la funci√≥n
user_deseado = "-AnimeIsMyThing-" # Reemplaza con un usuario
resultado_json = UserForGenre(user_deseado)
print(resultado_json)  # Imprimir el resultado en formato JSON

Usuario no encontrado

In [50]:
UserForGenre("-AnimeIsMyThing-")

'Usuario no encontrado'

Tercera Consulta:

In [51]:
# Unir columnas necesarias a√±o-juegos-recommend-sentiment
year_recommend_game = data_sentiment[["release_year", "item_name", "recommend", "sentiment_analysis"]]

In [52]:
year_recommend_game[["release_year"]] = year_recommend_game[["release_year"]].fillna(0)

C:\Users\56988\AppData\Local\Temp\ipykernel_15328\3326710474.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_recommend_game[["release_year"]] = year_recommend_game[["release_year"]].fillna(0)

In [53]:
year_recommend_game[["release_year"]] = year_recommend_game[["release_year"]].astype(int)

C:\Users\56988\AppData\Local\Temp\ipykernel_15328\237127839.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_recommend_game[["release_year"]] = year_recommend_game[["release_year"]].astype(int)

In [54]:
# Ver dataframe
year_recommend_game

       release_year                   item_name recommend  sentiment_analysis
0              2018              Counter-Strike      True                 2.0
1              2018       Team Fortress Classic      True                 2.0
2              2018               Day of Defeat      True                 2.0
3              2018          Deathmatch Classic      True                 2.0
4              2018   Half-Life: Opposing Force      True                 2.0
...             ...                         ...       ...                 ...
30473          2017                      Escape      True                 1.0
30474          2017               One Manga Day      True                 1.0
30475          2017               Shadow Hunter     False                 1.0
30476          2017  Transmissions: Element 120      True                 2.0
30477             0                SUPER DISTRO      True                 2.0

[30478 rows x 4 columns]

In [55]:
# Agrupar por a√±o y juego, contar las recomendaciones y obtener los top 3 juegos por a√±o
top3_recomendados = (year_recommend_game.groupby(["release_year", "item_name"])
                     .agg(recomendaciones=("recommend", "count"))
                     .reset_index()
                     .sort_values(by=["release_year", "recomendaciones"], ascending=[True, False])
                     .groupby("release_year")
                     .head(3))

# Ahora top3_recomendados contiene el top 3 de juegos m√°s recomendados por a√±o
top3_recomendados

       release_year                 item_name  recomendaciones
111               0            Counter-Strike                4
253               0  Half-Life 2: Episode One                4
410               0                  Portal 2                4
622            1981  Serious Sam Double D XXL                0
623            1982   Call of Duty: Black Ops                0
...             ...                       ...              ...
9500           2017               Dota 2 Test               51
9757           2017               Garry's Mod               43
11357          2018            Counter-Strike                2
11404          2018         Heroes & Generals                2
11416          2018             Left 4 Dead 2                2

[109 rows x 3 columns]

In [56]:
# Tercera consulta:
def UsersRecommend(anio: int): 
    '''Se ingresa el A√±o y la funci√≥n retorna el Top 3 de los juegos m√°s recomendados por los usuarios'''
    # Verificar si el a√±o proporcionado tiene datos en el DataFrame top3_recomendados
    if anio not in top3_recomendados["release_year"].unique():
        return f"No hay datos disponibles para el a√±o {anio}"

    # Filtrar el DataFrame top3_recomendados para el a√±o proporcionado
    top_games_year = top3_recomendados[top3_recomendados["release_year"] == anio]

    # Verificar si hay menos de 3 juegos para el a√±o consultado
    if len(top_games_year) < 1:
        return "No hay suficientes juegos para mostrar el top 3"

    # Reiniciar el √≠ndice del DataFrame filtrado por a√±o
    top_games_year = top_games_year.reset_index(drop=True)

    # Obtener el top 3 de juegos m√°s recomendados para el a√±o dado
    top_3_games = top_games_year.head(3)

    # Crear una lista con el formato especificado
    top_3_list = []
    for index, row in top_3_games.iterrows():
        game_rank = index + 1  # Usar el √≠ndice + 1 como n√∫mero de puesto
        game_dict = {"Puesto " + str(game_rank): row["item_name"]}
        top_3_list.append(game_dict)

    return top_3_list

In [57]:
# Ejemplo de uso: Obtener el top 3 de juegos recomendados para el a√±o 2014
anio = 2014
resultados = UsersRecommend(anio)
resultados

[{'Puesto 1': 'Left 4 Dead 2'},
 {'Puesto 2': 'Portal 2'},
 {'Puesto 3': "Don't Starve Together"}]

Cuarta consulta:

In [58]:
# Unir columnas necesarias a√±o, desarrolladores, recommend, sentiment_analysis
year_developer_recommend = data_final_sentiment[["release_year", "developer", "recommend", "sentiment_analysis"]]

In [59]:
year_developer_recommend[["release_year"]] = year_developer_recommend[["release_year"]].fillna(0)

C:\Users\56988\AppData\Local\Temp\ipykernel_15328\1803817347.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_developer_recommend[["release_year"]] = year_developer_recommend[["release_year"]].fillna(0)

In [60]:
year_developer_recommend[["release_year"]] = year_developer_recommend[["release_year"]].astype(int)

C:\Users\56988\AppData\Local\Temp\ipykernel_15328\3215423414.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  year_developer_recommend[["release_year"]] = year_developer_recommend[["release_year"]].astype(int)

In [61]:
# Ver dataframe
year_developer_recommend

       release_year      developer recommend  sentiment_analysis
0              2018      Kotoshiro      True                 2.0
1              2018      Kotoshiro      True                 2.0
2              2018      Kotoshiro      True                 2.0
3              2018      Kotoshiro      True                 2.0
4              2018      Kotoshiro      True                 2.0
...             ...            ...       ...                 ...
30473          2017  Studio SiestA      True                 1.0
30474          2017  Studio SiestA      True                 1.0
30475          2017  Studio SiestA     False                 1.0
30476          2017  Studio SiestA      True                 2.0
30477             0   Nelium Games      True                 2.0

[30478 rows x 4 columns]

In [62]:
# Obtener el top 3 de juegos menos recomendados por a√±o
top3_no_recomendados = year_developer_recommend.groupby(["release_year", "developer"]).size().reset_index(name="count")
top3_no_recomendados = top3_no_recomendados.sort_values(["release_year", "count"]).groupby("release_year").head(3)

top3_no_recomendados

      release_year             developer  count
4                0            Futuremark      1
6                0    Grotta Game Studio      1
7                0          K Bros Games      1
32            1983  Digital Leisure Inc.      3
33            1984  Digital Leisure Inc.      3
...            ...                   ...    ...
4896          2017         Aerosoft GmbH      1
4912          2017          Alex's Daddy      1
7123          2018      Games by Brundle      1
7146          2018             Steel Fox      1
7108          2018   Blaiz Entertainment      2

[97 rows x 3 columns]

In [63]:
# Cuarta consulta:
def UsersWorstDeveloper(anio: int):
    '''Se ingresa el A√±o y la funci√≥n retorna el top 3 de Desarrolladores con MENOS recomendaciones por Usuarios'''
    # Verificar si el a√±o proporcionado tiene datos en el DataFrame top3_no_recomendados
    if anio not in top3_no_recomendados["release_year"].unique():
        return f"No hay datos disponibles para el a√±o {anio}"

    # Filtrar el DataFrame top3_no_recomendados para el a√±o proporcionado
    top_games_year = top3_no_recomendados[top3_no_recomendados["release_year"] == anio]

    # Verificar si hay menos de 3 juegos para el a√±o consultado
    if len(top_games_year) < 1:
        return "No hay suficientes juegos para mostrar el top 3 menos recomendados"

    # Reiniciar el √≠ndice del DataFrame filtrado por a√±o
    top_games_year = top_games_year.reset_index(drop=True)

    # Obtener el top 3 de juegos m√°s recomendados para el a√±o dado
    top_3_games = top_games_year.head(3)

    # Crear una lista con el formato especificado
    top_3_list = []
    for index, row in top_3_games.iterrows():
        game_rank = index + 1  # Usar el √≠ndice + 1 como n√∫mero de puesto
        game_dict = {"Puesto " + str(game_rank): row["developer"]}
        top_3_list.append(game_dict)

    return top_3_list

In [64]:
# Ejemplo de uso: Obtener el top 3 de desarrolladores menos recomendados
anio = 2014
resultados = UsersWorstDeveloper(anio)
resultados

[{'Puesto 1': '2by3 Games'},
 {'Puesto 2': '343 Industries,Vanguard Games'},
 {'Puesto 3': '88mm'}]

Quinta consulta:

In [65]:
# Unir columnas necesarias desarrolladores, sentiment_analysis
developer_sentiment = data_final_sentiment[["developer", "sentiment_analysis", "release_year"]]

In [66]:
developer_sentiment[["release_year"]] = developer_sentiment[["release_year"]].fillna(0)

C:\Users\56988\AppData\Local\Temp\ipykernel_15328\1229011352.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  developer_sentiment[["release_year"]] = developer_sentiment[["release_year"]].fillna(0)

In [67]:
developer_sentiment[["release_year"]] = developer_sentiment[["release_year"]].astype(int)

C:\Users\56988\AppData\Local\Temp\ipykernel_15328\3304827221.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  developer_sentiment[["release_year"]] = developer_sentiment[["release_year"]].astype(int)

In [68]:
# Ver dataframe
developer_sentiment

           developer  sentiment_analysis  release_year
0          Kotoshiro                 2.0          2018
1          Kotoshiro                 2.0          2018
2          Kotoshiro                 2.0          2018
3          Kotoshiro                 2.0          2018
4          Kotoshiro                 2.0          2018
...              ...                 ...           ...
30473  Studio SiestA                 1.0          2017
30474  Studio SiestA                 1.0          2017
30475  Studio SiestA                 1.0          2017
30476  Studio SiestA                 2.0          2017
30477   Nelium Games                 2.0             0

[30478 rows x 3 columns]

In [69]:
# Filtrar las filas donde el an√°lisis de sentimiento no es nulo
filtered_df = developer_sentiment[developer_sentiment["sentiment_analysis"].notnull()]

# Mapear los valores de 'sentiment_analysis' a los tipos de sentimiento
sentiment_mapping = {0: "Negativo", 1: "Neutral", 2: "Positivo"}
filtered_df["sentiment_label"] = filtered_df["sentiment_analysis"].map(sentiment_mapping)

# Agrupar por 'release_year' y 'sentiment_label', contar registros y reindexar para tener una estructura de dataframe adecuada
result = filtered_df.groupby(["release_year", "sentiment_label"]).size().reset_index(name="count")

# Reestructurar los datos para tener un DataFrame con los tres tipos de sentimientos como columnas y el a√±o como columna independiente
conteo_sentimientos = result.pivot(index="release_year", columns="sentiment_label", values="count").fillna(0).reset_index()

# Mostrar el resultado
print(conteo_sentimientos)

sentiment_label  release_year  Negativo  Neutral  Positivo
0                           0     105.0     93.0     203.0
1                        1983       1.0      1.0       0.0
2                        1986       1.0      0.0       0.0
3                        1988       0.0      0.0       1.0
4                        1989       1.0      0.0       2.0
5                        1990       1.0      1.0       0.0
6                        1991       1.0      1.0       1.0
7                        1992       0.0      0.0       5.0
8                        1993       4.0      3.0      11.0
9                        1994       2.0      3.0       7.0
10                       1995       1.0      2.0       5.0
11                       1996       5.0      6.0       8.0
12                       1997       3.0      5.0       5.0
13                       1998       6.0      3.0       7.0
14                       1999       4.0      2.0      10.0
15                       2000       3.0      1.0      11.0
16                       2001       4.0      2.0       7.0
17                       2002       0.0      2.0       5.0
18                       2003       9.0      8.0      13.0
19                       2004       4.0      3.0       6.0
20                       2005       2.0      3.0      20.0
21                       2006       8.0     11.0      43.0
22                       2007      15.0     11.0      51.0
23                       2008      18.0     21.0      51.0
24                       2009      41.0     17.0      92.0
25                       2010      42.0     36.0     148.0
26                       2011      64.0     52.0     204.0
27                       2012     104.0     78.0     230.0
28                       2013     126.0    125.0     355.0
29                       2014     230.0    193.0     522.0
30                       2015     360.0    332.0     827.0
31                       2016     486.0    391.0    1000.0
32                       2017    1479.0   1348.0    2765.0
33                       2018      21.0     45.0      87.0

C:\Users\56988\AppData\Local\Temp\ipykernel_15328\3287631640.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df["sentiment_label"] = filtered_df["sentiment_analysis"].map(sentiment_mapping)

In [70]:
# Quinta consulta:
def SentimentAnalysis(desarrollador: str): 
    '''Se ingresa el Desarrollador y la funci√≥n retorna con la lista de registros totales de rese√±as Negativa, Positiva, o Neutral de los Usuarios'''
    # Filtrar las rese√±as por el desarrollador dado
    rese√±as_desarrolladora = developer_sentiment[developer_sentiment["developer"] == desarrollador]

    # Contar las rese√±as con sentimiento negativo, positivo o neutro
    sentimiento_negativo = rese√±as_desarrolladora[rese√±as_desarrolladora["sentiment_analysis"] == 0].shape[0]
    sentimiento_neutral = rese√±as_desarrolladora[rese√±as_desarrolladora["sentiment_analysis"] == 1].shape[0]
    sentimiento_positivo = rese√±as_desarrolladora[rese√±as_desarrolladora["sentiment_analysis"] == 2].shape[0]

    # Crear el diccionario de resultados
    resultado = {desarrollador: {"Negative": sentimiento_negativo, "Neutral": sentimiento_neutral, "Positive": sentimiento_positivo}}

    return resultado

In [71]:
SentimentAnalysis("Studio SiestA")

{'Studio SiestA': {'Negative': 0, 'Neutral': 3, 'Positive': 1}}

In [72]:
# Guardar dataframes a parquet
genres_year_playtime.to_parquet('genres_year_playtime.parquet')
max_playtime_by_genre_year.to_parquet('max_playtime_by_genre_year.parquet')
user_year_playtime.to_parquet('user_year_playtime.parquet')
year_recommend_game.to_parquet('year_recommend_game.parquet')
top3_recomendados.to_parquet('top3_recomendados.parquet')
top3_no_recomendados.to_parquet('top3_no_recomendados.parquet')
developer_sentiment.to_parquet('developer_sentiment.parquet')